/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Metal Block.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Block(props) {
  const { nodes, materials } = useGLTF("/Block.glb");

  console.log("nodes", nodes);
  console.log("materials", materials);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Block_Metal.geometry}
        material={materials.Atlas}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/Metal Block.glb");
