/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Metal Block.glb --transform 
Files: Metal Block.glb [45.56KB] > Metal Block-transformed.glb [7.53KB] (83%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Metal Block-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Block_Metal.geometry}
        material={materials.Atlas}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/Metal Block-transformed.glb");
